# Generated by Django 5.2 on 2025-05-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('allergy', models.CharField(blank=True, max_length=100, null=True)),
                ('appearance', models.TextField()),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pets/')),
            ],
        ),
    ]
